# Generated by Django 4.1.4 on 2022-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupitor_app', '0002_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel',
            name='id',
        ),
        migrations.AddField(
            model_name='excel',
            name='e_id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
