# Generated by Django 4.1.4 on 2022-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupitor_app', '0003_remove_excel_id_excel_e_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='jupitorExcel',
            fields=[
                ('e_id', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('e_division', models.CharField(max_length=100)),
                ('e_title', models.CharField(max_length=100)),
                ('e_date', models.DateField()),
                ('e_notes', models.CharField(max_length=100)),
                ('e_bunting', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='excel',
        ),
    ]
